version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid/" # assumed current dir contains browsers.json
      - "$PWD/video/:/opt/selenoid/video/" # 
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/logs/:/opt/selenoid/logs/"
    environment: 
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video/
    command: -limit 10 -service-startup-timeout 1m -retry-count 3 -enable-file-upload -log-output-dir /opt/selenoid/logs
 
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    restart: always
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
